<?php // --- Fichier: template-parts/modal-project.php --- ?>
<div id="project-modal" class="modal-overlay fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-[70] opacity-0 pointer-events-none">
    <div class="modal-container bg-white w-full max-w-2xl rounded-xl shadow-2xl p-8 transform scale-95">
        <div class="flex justify-between items-start"><h2 class="text-2xl font-bold text-slate-900" data-lang="modalTitle">Proposer un projet innovant</h2><button id="close-modal-btn" class="text-slate-500 hover:text-slate-800">&times;</button></div>
        <p class="mt-2 text-slate-600" data-lang="modalSubtitle">Décrivez votre idée ci-dessous. Notre assistant IA peut vous aider à la peaufiner !</p>
        <div class="mt-6"><label for="project-idea-input" class="block text-sm font-medium text-slate-700" data-lang="modalIdeaLabel">Votre idée de projet :</label><textarea id="project-idea-input" rows="4" class="mt-1 block w-full rounded-md border-slate-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500" placeholder="..." data-lang-placeholder="modalIdeaPlaceholder"></textarea></div>
        <div class="mt-4"><button id="improve-desc-btn" class="w-full sm:w-auto flex items-center justify-center gap-2 bg-emerald-600 text-white px-5 py-2.5 rounded-lg font-semibold hover:bg-emerald-700 transition duration-300 shadow"><span data-lang="modalImproveBtn">✨ Améliorer ma description</span><svg id="loading-spinner-modal" class="animate-spin h-5 w-5 text-white hidden" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg></button></div>
        <div id="improved-desc-container" class="mt-6 hidden"><label for="project-idea-output" class="block text-sm font-medium text-slate-700" data-lang="modalSuggestedDesc">Description suggérée par l'IA :</label><div id="project-idea-output" class="mt-1 p-4 block w-full rounded-md bg-slate-50 border border-slate-200 min-h-[100px] text-sm"></div></div>
        <div class="mt-8 pt-6 border-t border-slate-200 flex justify-end gap-4"><button id="cancel-modal-btn" class="bg-white text-slate-700 px-6 py-2 rounded-lg hover:bg-slate-100 transition duration-300 ring-1 ring-slate-200" data-lang="modalCancel">Annuler</button><button class="bg-emerald-600 text-white px-6 py-2 rounded-lg hover:bg-emerald-700 transition duration-300 shadow" data-lang="modalSubmit">Soumettre le projet</button></div>
    </div>
</div>